#
# Makefile for the Linux Kernel SOC fsl specific device drivers
#

obj-$(CONFIG_QUICC_ENGINE)		+= qe/
obj-$(CONFIG_CPM)			+= qe/
obj-$(CONFIG_LS1_SOC_DRIVERS)		+= ls1/
obj-$(CONFIG_LS_SOC_DRIVERS)		+= ls2-console/
